---
- name: setup webserver
  hosts: all
  become: true
  tasks:
    - name: httpd installed
      yum:
        name: httpd
        state: latest
    - name: custom index.html
      copy:
        dest: /var/www/html/index.html
        content: |
                    Custom Web Page
    - name: httpd service enabled
      service:
        name: httpd
        enabled: true
        state: started
